create table tb_employees (employees_id int8 generated by default as identity, name varchar(255), email varchar(255), department varchar(255), salary double, birth_date date, primary key(employees_id));
alter table if exists tb_score add constraint FKl8lgmbrjoav0thqqtqx6vrr4k foreign key (employees_id) references tb_employees;
INSERT INTO tb_employees(name,email,department,salary,birth_date) VALUES ('Anakin Skywalker','skywalker@ssys.com.br','Architecture',4000.0,'1983-01-01');
INSERT INTO tb_employees(name,email,department,salary,birth_date) VALUES ('Obi-Wan Kenobi','kenobi@ssys.com.br','Back-End',3000.0,'1977-01-01');
INSERT INTO tb_employees(name,email,department,salary,birth_date) VALUES ('Leia Organa','organa@ssys.com.br','DevOps',5000.0,'1980-01-01');